DEPARTMENT_MAP = {
    "Leadership": "Management",
    "Finance": "Finance  - D",
    "Procurement": "Purchase",
    "Facilities": "Facility Management - D",
    "Kitchen (Production)": "Kitchen - D",
    "Packaging": "Plating and Packaging - D",
    "Logistics (Delivery)": "Logistics - D",
    "Technology": "Tech - D",
    "Customer Service": "Customer Service",
    "Operations": "Operations",
    "Sales": "Sales",
    "Marketing": "Marketing",
}

SCORECARD_VALUES = [
    ("Acquisition", "310 / QAR 210", "310 / QAR 210", "450 / QAR 160"),
    ("Retention", "62%", "62%", "71%"),
    ("Margin", "31%", "31%", "38%"),
]

DEMO_BETS = [
    {"rank": 1, "short_name": "Smart defaults", "door": "Evidence", "then_what": "Fewer non-selecting customers leave", "number_today": "41", "number_want": "28", "unit": "%", "by_when": "2026-12-15", "main_score": "Retention", "so_what": "Non-selectors receive meals they like WITHOUT having to select — default-day complaints fall", "so_what_today": "4.2", "so_what_pass_mark": "1.5 complaints per 1,000 meals", "what": "Preference bubbles at onboarding + a rule in the backend that assigns defaults from preferences and past ratings", "tiny_test": "CS hand-picks defaults for 100 non-selectors for 2 weeks using their preferences; count complaints vs the other non-selectors", "tiny_test_by": "2026-10-09", "owner": "Product owner", "department": "Technology", "next_step": "Pull non-selector cohort and churn split from ERPNext", "next_step_by": "2026-09-18", "next_step_who": "Data analyst", "colour": "G", "last_updated": "2026-09-14", "blocker": "Automated ML defaults; swipe UI for selectors", "doors_opened": "Automated smart defaults; swipe selection UI; component kitchen personalisation"},
    {"rank": 2, "short_name": "New factory live", "door": "Single path", "then_what": "MAP production capacity exists", "number_today": "0", "number_want": "2,000", "unit": "meals per day", "by_when": "2026-11-30", "main_score": "Margin", "also_helps": "Retention", "so_what": "Civil Defence approves and one MAP line runs", "so_what_today": "0", "so_what_pass_mark": "1 line commissioned, 500 meals/day in week 1", "what": "New facility with Civil Defence approval and one MAP production line", "tiny_test": "Not applicable (one road only). Milestone 1: approval. Milestone 2: one line running", "tiny_test_by": "2026-10-31", "owner": "Ops lead", "department": "Operations", "next_step": "Submit remaining Civil Defence documents", "next_step_by": "2026-09-20", "next_step_who": "Facilities lead", "colour": "Y", "last_updated": "2026-09-12", "blocker": "Waiting on inspection date", "who_can_unblock": "Civil Defence", "doors_opened": "Retail / hotel / airline MAP meals; B2B at scale; Essentials at retail"},
    {"rank": 3, "short_name": "Lego kitchen", "door": "Evidence", "then_what": "Kitchen hours per 1,000 meals fall (also: special-diet coverage 55% → 90%)", "number_today": "62", "number_want": "45", "unit": "kitchen hours per 1,000 meals", "by_when": "2027-02-28", "main_score": "Margin", "also_helps": "Retention", "so_what": "Cooking components and assembling per customer takes fewer hours and serves more diets, with the same taste", "so_what_today": "62 h / 55% diets", "so_what_pass_mark": "≤ 55 h AND ≥ 75% diets on the 5 pilot dishes", "what": "50 dishes broken into components; kitchen cooks components, assembles per order; ERP + app updated AFTER the pilot proves it", "tiny_test": "5 dishes broken into components, cooked component-level for 2 weeks on paper sheets; log hours, waste, taste variance, diets servable", "tiny_test_by": "2026-10-23", "owner": "Head chef", "department": "Kitchen (Production)", "next_step": "Pick the 5 pilot dishes and list their components", "next_step_by": "2026-09-25", "next_step_who": "Head chef", "colour": "G", "last_updated": "2026-09-14", "blocker": "Hyper-personalisation; allergy-safe certified line", "doors_opened": "Hyper-personalisation; allergy-safe certified line"},
    {"rank": 4, "short_name": "New positioning test", "door": "Evidence", "then_what": "More strangers who see our ads buy", "number_today": "2.1", "number_want": "3.0", "unit": "of 100 visitors buy", "by_when": "2026-10-31", "main_score": "Acquisition", "also_helps": "Retention", "so_what": "Strangers understand the taste-first message and click through", "so_what_today": "1.1%", "so_what_pass_mark": "1.8% click-through on cold audiences", "what": "Separate landing page + 3 ad sets with the taste-first message", "tiny_test": "4 weeks of cold traffic to the new page, existing customers excluded", "tiny_test_by": "2026-10-27", "owner": "Marketing lead", "department": "Marketing", "next_step": "Substantiation page live (launch blocker)", "next_step_by": "2026-09-22", "next_step_who": "Content lead", "colour": "R", "last_updated": "2026-09-05", "blocker": "Substantiation page not started", "who_can_unblock": "Marketing lead", "doors_opened": "Roll positioning to all channels; founder content engine"},
    {"rank": 5, "short_name": "Tech ships without CEO", "door": "Single path", "then_what": "App releases go out with no founder involvement", "number_today": "0", "number_want": "1", "unit": "releases", "by_when": "2026-11-30", "main_score": "Margin", "so_what": "A CTO owns technical decisions, so the CEO is not the bottleneck", "so_what_today": "0", "so_what_pass_mark": "CTO in seat by 15 Oct", "what": "Hire a CTO", "tiny_test": "Not applicable (one road only). Milestone: offer accepted", "tiny_test_by": "2026-10-15", "owner": "CEO", "department": "Leadership", "next_step": "Second call + trial task with shortlisted candidate", "next_step_by": "2026-09-17", "next_step_who": "CEO", "colour": "G", "last_updated": "2026-09-13", "doors_opened": "Tech roadmap owned by CTO"},
    {"rank": 6, "short_name": "B2B pilot", "door": "Evidence", "then_what": "Corporate accounts pay monthly", "number_today": "0", "number_want": "120,000", "unit": "QAR per month (5 accounts)", "by_when": "2026-12-31", "main_score": "Acquisition", "also_helps": "Margin", "so_what": "One company buys, gets delivered daily from the current kitchen, and renews — proving the sales cycle and margin", "so_what_today": "0", "so_what_pass_mark": "1 pilot account renewed after month 1 at ≥ 30% margin", "what": "One pilot account (50 meals/day) served from the current kitchen", "tiny_test": "Sell and serve one pilot account for 6 weeks before any capacity is committed", "tiny_test_by": "2026-10-31", "owner": "Sales lead", "department": "Sales", "next_step": "Confirm 200 meals/day B2B capacity from current kitchen", "next_step_by": "2026-09-19", "next_step_who": "Ops lead", "colour": "Y", "last_updated": "2026-09-11", "blocker": "Needs Bet 2 to scale beyond pilot", "who_can_unblock": "Ops lead", "doors_opened": "B2B at scale (20 accounts)"},
    {"rank": 7, "short_name": "50-dish menu", "door": "Evidence", "then_what": "Less prepared food is wasted", "number_today": "9", "number_want": "5", "unit": "% of prepared food wasted", "by_when": "2027-01-31", "main_score": "Margin", "also_helps": "Retention", "so_what": "Most of what customers order is already the same ~50 dishes, so removing the rest loses no orders", "so_what_today": "unknown", "so_what_pass_mark": "top 50 dishes ≥ 95% of orders", "what": "Fixed menu of 50 dishes instead of 58 rotating", "tiny_test": "Data pull: share of orders by dish, last 90 days. If top 50 ≥ 95%, go", "tiny_test_by": "2026-09-30", "owner": "Ops lead", "department": "Operations", "next_step": "Run dish-volume query", "next_step_by": "2026-09-18", "next_step_who": "Data analyst", "colour": "G", "last_updated": "2026-09-14", "blocker": "Component kitchen on a stable base (feeds Bet 3)"},
]

DEMO_PROMISES = [
    (1, "Non-selector cohort and churn split, last 6 months", "Technology", "Data analyst", "2026-09-18", False, None, "Sheet with cohort sizes and 60-day churn for selectors vs non-selectors", "Product owner", False, None, 0, 0, None),
    (1, "Manual preference-based defaults assigned for 100 customers, 2 weeks", "Customer Service", "CS lead", "2026-09-25", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (1, "Onboarding preference field designed and tested on 5 customers (≥80% complete it)", "Technology", "UX designer", "2026-09-11", True, "2026-09-15", "Figma file + 5-customer test log showing ≥80% completion + dev handoff notes", "Backend lead", True, "2026-09-15", 2, 1, "v2 returned: no 5-customer test log (DoD line 2). v1 return 'colours feel off' had no DoD line → counted against receiver."),
    (1, "Default-assignment rule live in backend (reads preferences + past ratings)", "Technology", "Backend lead", "2026-10-16", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (1, "Preference field live in app onboarding", "Technology", "App lead", "2026-10-23", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (2, "Remaining Civil Defence documents submitted", "Facilities", "Facilities lead", "2026-09-20", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (2, "Cold-room and MAP equipment purchase orders placed", "Procurement", "Procurement lead", "2026-09-12", True, "2026-09-12", "3 POs issued and supplier confirmations attached", "Ops lead", False, None, 0, 0, None),
    (2, "Facility fit-out budget released", "Finance", "Finance lead", "2026-09-26", True, "2026-09-24", "Funds in the project account", "Ops lead", True, "2026-09-24", 0, 0, None),
    (3, "5 pilot dishes broken into component lists", "Kitchen (Production)", "Head chef", "2026-09-25", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (3, "2-hour walkthrough of component production with UX designer", "Operations", "Ops lead", "2026-10-09", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (3, "Component pilot run 2 weeks on paper: hours, waste, taste variance logged", "Kitchen (Production)", "Head chef", "2026-10-23", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (3, "Packaging spec for assembled-component meals", "Packaging", "Packaging lead", "2026-10-16", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (3, "ERP component/assembly spec written FROM pilot results", "Technology", "ERP lead", "2026-11-06", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (4, "Substantiation page: receipt for every factual claim", "Marketing", "Content lead", "2026-09-22", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (4, "3 ad sets + separate landing page live, existing customers excluded", "Marketing", "Marketing lead", "2026-09-29", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (6, "Confirm 200 meals/day B2B capacity from current kitchen", "Operations", "Ops lead", "2026-09-19", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (6, "B2B sales deck", "Marketing", "Marketing lead", "2026-10-01", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (6, "Credit terms and invoicing flow for corporate accounts", "Finance", "Finance lead", "2026-10-01", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (6, "Delivery route plan for one corporate site (50 meals/day)", "Logistics (Delivery)", "Logistics lead", "2026-10-08", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
    (7, "Dish-volume query: share of volume by dish, last 90 days", "Technology", "Data analyst", "2026-09-18", False, None, "(write what done means)", "bet_owner", False, None, 0, 0, None),
]

DEPARTMENT_STANDING = [
    ("Leadership", "Board reviewed by CEO (days this week)", "5", "5", "Decisions escalated resolved within 48h (%)", "100%", "100%"),
    ("Finance", "Supplier invoices paid on time (%)", "95%", "92%", "Month close done by (working day)", "5", "6"),
    ("Procurement", "Purchase orders placed within 2 days of request (%)", "90%", "88%", "Stock-outs of key ingredients (count)", "0", "1"),
    ("Facilities", "Open maintenance tickets older than 7 days", "0", "2", "Compliance items on time (%)", "100%", "100%"),
    ("Kitchen (Production)", "Meals produced vs plan (%)", "100%", "99%", "Taste-check fails per 1,000 meals", "≤1.5", "3.1"),
    ("Packaging", "Packaging errors per 1,000 meals", "≤1", "1.4", "Packaging stock cover (days)", "≥14", "12"),
    ("Logistics (Delivery)", "Deliveries on time (%)", "97%", "95%", "Wrong-meal deliveries per 1,000", "≤1", "2"),
    ("Operations", "Daily production plan issued by 6pm (days/week)", "6", "6", "Prep waste (%)", "5%", "9%"),
    ("Technology", "App crash-free sessions (%)", "99.5%", "99.2%", "Critical bugs open > 3 days", "0", "1"),
    ("Customer Service", "Complaints resolved within 24h (%)", "95%", "90%", "Cancellations with a reason tagged (%)", "100%", "70%"),
    ("Sales", "B2B proposals sent per week", "3", "1", "Pipeline value (QAR)", "300k", "80k"),
    ("Marketing", "New subscribers this month", "450", "310", "Cost per new customer (QAR)", "160", "210"),
]

PEOPLE_STANDING = [
    ("Ops lead", "Operations", "Head of Operations", "Daily production plan issued by 6pm (days/wk)", "6", "6", "Prep waste %", "5%", "9%"),
    ("Marketing lead", "Marketing", "Head of Marketing", "New subscribers this month", "450", "310", "Cost per new customer (QAR)", "160", "210"),
    ("UX designer", "Technology", "Product / UX Designer", "Designs accepted first time (%)", "80%", "33%", "Design turnaround (working days)", "10", "14"),
    ("Backend lead", "Technology", "Backend Engineer", "Critical bugs open > 3 days", "0", "1", "Releases shipped on date (%)", "90%", "100%"),
    ("CS lead", "Customer Service", "Head of Customer Service", "Complaints resolved within 24h (%)", "95%", "90%", "Cancellations tagged with a reason (%)", "100%", "70%"),
    ("Finance lead", "Finance", "Finance Manager", "Supplier invoices paid on time (%)", "95%", "92%", "Month close by working day", "5", "6"),
    ("Head chef", "Kitchen (Production)", "Head Chef", "Taste-check fails per 1,000 meals", "≤1.5", "3.1", "Meals produced vs plan (%)", "100%", "99%"),
    ("Dietitian lead", "Customer Service", "Lead Dietitian", "Check-ins completed per week", "40", "0", "Plan adjustments logged per week", "20", "0"),
    ("Logistics lead", "Logistics (Delivery)", "Delivery Manager", "Deliveries on time (%)", "97%", "95%", "Wrong-meal deliveries per 1,000", "≤1", "2"),
    ("Data analyst", "Technology", "Data Analyst", "Requested data pulls delivered within 3 days (%)", "90%", "100%", "Dashboards refreshed weekly (Y/N)", "Y", "Y"),
]

DEMO_FUTURE_BETS = [
    ("Retail / hotel / airline MAP meals, QAR X per month", 2, "Acquisition", "2027-01-15", "CEO", "Needs capacity first; bundling it turns a factory move into a strategy discussion"),
    ("B2B at scale: 20 accounts, QAR 500k per month", 6, "Acquisition", "2027-02-01", "Sales lead", "Pilot must prove sales cycle and margin before capacity is committed"),
    ("Hyper-personalisation per health goal at 90%+ coverage", 3, "Retention", "2027-03-01", "Head chef", "Requires the component kitchen to exist and be stable"),
    ("Allergy-safe certified line", 3, "Acquisition", "2027-04-01", "Ops lead", "Certification only possible on component production"),
    ("Automated smart defaults (rules → ML)", 1, "Retention", "2026-12-01", "Backend lead", "Rule-based version must run 8 weeks first"),
    ("Swipe selection UI for selecting customers: selection completion X% → Y%", 1, "Retention", "2026-12-15", "App lead", "Different cohort from Bet 1; would break attribution"),
    ("Hosted community (SIGNAL bet): +10 retention points for group members — candidate for the reserved seat", None, "Retention", "2026-10-06", "Product owner", "Waits for Step 0 baseline and a free Board seat"),
    ("Dietitian-led premium tier", None, "Margin", "2027-03-01", "Product owner", "Depends on progress check-in test"),
    ("MAP Essentials at retail scale", 2, "Acquisition", "2027-02-01", "CEO", "Needs factory line commissioned"),
]

PARKING_LOT = [
    ("Swipe ('tinder') meal selection UI", "Better selection for customers who DO select", "App lead", "2026-09-14", "2026-12-14", True),
    ("Brand Operating System portal (11 HTML docs)", "Strategy reference; too heavy to run as an operating tool", "CEO", "2026-09-14", "2026-12-14", False),
    ("Amphitheatre event programme", "Founder-led brand events in the factory", "Marketing lead", "2026-09-14", "2027-01-15", False),
    ("Flowers / occasion gifts", "Surprise and delight", "CS lead", "2026-09-16", "2026-12-16", False),
    ("ML meal recommendation", "Personalisation beyond rules", "Backend lead", "2026-09-14", "2027-01-15", False),
]

DEMO_BRIEFS = [
    {"title": "Smart defaults for non-selecting customers", "door": "Evidence", "door_detail": "'Didn't like meals' is the #1 exit reason and 93% of those are non-selectors.", "problem": "~38% of subscribers never select meals and receive default dishes. Their 60-day churn is ~41 of 100 vs ~24 of 100 for customers who select. Default-day complaints run ~3x selected-day complaints. Involved: CS, backend, app, UX. Data from ERPNext.", "then_what": "Non-selector churn falls from 41 to 28 of 100 (60-day) by 15 Dec 2026. Score: Retention.", "so_what": "Non-selectors receive meals they like WITHOUT having to select anything. Number: default-day complaints 4.2 → 1.5 per 1,000 meals in the tiny test.", "what": "Preference bubbles at onboarding + a backend rule that assigns defaults from preferences and past ratings. Nothing else.", "tradeoffs": "Speed beats polish; rule-based beats ML until rules have run 8 weeks.", "tiny_test": "CS manually assigns defaults for 100 non-selectors for 2 weeks using onboarding preference bubbles + past ratings. Compare complaints against the other non-selectors. No code.", "decision_rule": "GO if complaints drop ≥50%; re-brief if complaints drop but churn is unchanged; stop if complaints do not move.", "not_doing": "Swipe selection UI, Lego kitchen, menu changes, or anything that asks the non-selector to do more.", "promises_needed": "Data analyst cohort split; CS manual assignment; UX preference field; Backend rule; App field live.", "future_doors": "Automated ML defaults, swipe UI for selectors, and preference data feeding Lego personalisation.", "outcomes": [(1, "60-day churn, non-selector cohort", "41 of 100", "28 of 100", "60-day", "Product owner"), (2, "Default-day complaints per 1,000 meals", "4.2", "1.5", "tiny test", "Product owner"), (3, "Onboarding preference-step completion", "n/a", "≥80%", "5-customer test", "UX designer")]},
    {"title": "Component (Lego) kitchen", "door": "Evidence", "door_detail": "'Didn't like meals' and 'service issue' exit reasons; one production change moves four numbers directly.", "problem": "We produce 58 rotating dishes at dish level. Only ~55% of customer restriction profiles can be served; kitchen runs ~62 hours per 1,000 meals; 'not as expected' complaints run ~3.1 per 1,000.", "then_what": "Kitchen hours per 1,000 meals 62 → 45 and diets servable 55% → 90% by 28 Feb 2027. Scores: Margin and Retention.", "so_what": "Cooking components and assembling per customer takes fewer hours and serves more diets with the same taste.", "what": "50 dishes broken into components; kitchen cooks components and assembles per order. ERP, UX and app changes follow only after the pilot.", "tradeoffs": "Consistency beats variety; cost beats personalisation; unresolved conflicts go to the Chief of Staff.", "tiny_test": "Pick 5 dishes and produce component-level for 2 weeks on paper, logging hours, waste, taste fails, and diets served.", "decision_rule": "GO if hours ≤55 and diets ≥75%; re-brief if only one moves; otherwise stop/park.", "not_doing": "Swipe selection UI, delivery-logistics changes, menu simplification, and ERP/app work before the pilot.", "promises_needed": "Head chef components and pilot; Ops walkthrough; Packaging spec; ERP specification after pilot results.", "future_doors": "Full hyper-personalisation, allergy-safe certified line, and component-based launches.", "outcomes": [(1, "Special-diet coverage", "55%", "90%", "by 28 Feb 2027", "Head chef"), (2, "Prep cost — kitchen hours per 1,000 meals", "62 h", "45 h", "by 28 Feb 2027", "Head chef"), (3, "Consistency — complaints per 1,000 meals", "3.1", "≤1.5", "pilot", "Head chef"), (4, "Personalisation — non-selector meal rating", "3.6 / 5", "improve", "pilot", "Product owner")]},
    {"title": "Progress check-in", "door": "Evidence", "door_detail": "'No results / plateaued' is the #2 exit reason.", "problem": "~31% of cancellations say 'no results / plateaued'. Customers who lose weight in month 1 and then stall get no contact; their 60-day churn is ~39 of 100 vs ~22 of 100 for customers who keep seeing results.", "then_what": "Churn of plateaued customers 39 → 28 of 100 by 15 Dec 2026. Score: Retention.", "so_what": "A week-4 human check-in leads to a plan adjustment, and adjusted customers keep going.", "what": "A 3-question call script plus adjustment logged in ERPNext. The CS follow-up call is a cheaper format of the same so-what.", "tradeoffs": "Human check-in beats automated message until the test proves otherwise; dietitian time is capped at 15 minutes per customer.", "tiny_test": "Dietitian calls 100 customers at week 4; 100 matched customers receive nothing. Measure reach and adjustments at week 2 and churn at week 8.", "decision_rule": "GO if reach ≥80%, adjustments ≥50%, and week-8 churn is ≥8 points below control; re-brief for a 3–8-point gap; otherwise stop.", "not_doing": "Flowers, gifts, community features, app changes, or automation before the manual test reads.", "promises_needed": "Data analyst plateau cohort; Dietitian 100 calls; CS control group; Product read-out.", "future_doors": "Automated progress nudges, dietitian-led premium tier, and transformation stories as content.", "outcomes": [(1, "60-day churn, customers who plateau by week 4", "39 of 100", "28 of 100", "60-day", "Dietitian lead"), (2, "Week-4 customers reached", "0%", "80%", "tiny test", "Dietitian lead"), (3, "Plan adjustments after check-in", "0", "50%", "tiny test", "Dietitian lead")]},
]
